# docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: resources/Dockerfile
    command: uvicorn run:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8001:8000
